---
- hosts: servers

  vars:
    app_path: /home/linuxtips/node

  tasks:

    - name: Set Variable
      set_fact:
        pm2_app_name: "node-app"

    - name: Create New Folder
      file: 
        dest: "{{ app_path }}"
        mode: 0755
        recurse: yes
        state: directory

    - name: Clone the Repository
      git:
        repo: https://github.com/savagz/app-node-express-base.git
        dest: "{{ app_path }}"

    - name: Install globally package "pm2".
      npm:
        name: pm2
        global: yes
      become: yes

    - name: Install packages 'npm install'
      npm: 
        path: "{{ app_path }}"
        state: present

    - name: Delete Old pm2 process
      command: pm2 delete {{ pm2_app_name }}
      ignore_errors: yes

    - name: Start pm2
      command: pm2 start {{ app_path }}/bin/www --name {{ pm2_app_name }}
