---
- hosts: servers
  become: true

  tasks:

    - name: Setup Nodejs
      shell: curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -
      args:
        warn: false

    - name: Update Apt
      apt: update_cache=yes

    - name: Install Nodejs
      apt: name=nodejs state=latest